import { type Button } from "../Button/Button";

export const buttons: Button[] = [
  {
    title: 7,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: 8,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: 9,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: "del",
    bgColor: "bg-blue",
    bgColorSecondary: "bg-blue-faded",
    bgColorHover: "hover:bg-blue-hover",
    textColor: "text-special-btn",
    isNumber: false,
  },
  {
    title: 4,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: 5,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: 6,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: "+",
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: false,
  },
  {
    title: 1,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: 2,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: 3,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: "-",
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: false,
  },
  {
    title: ".",
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: 0,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: true,
  },
  {
    title: "/",
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: false,
  },
  {
    title: "x",
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-main-text",
    isNumber: false,
  },
  {
    title: "reset",
    bgColor: "bg-blue",
    bgColorSecondary: "bg-blue-faded",
    bgColorHover: "hover:bg-blue-hover",
    textColor: "text-special-btn",
    spansTwoColumns: true,
    isNumber: false,
  },
  {
    title: "=",
    bgColor: "bg-danger",
    bgColorSecondary: "bg-danger-faded",
    bgColorHover: "hover:bg-danger-hover",
    textColor: "text-special-btn",
    spansTwoColumns: true,
    isNumber: false,
  },
];
