// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Aggregation } from '../openmeteo_sdk/aggregation';
import { Unit } from '../openmeteo_sdk/unit';
import { Variable } from '../openmeteo_sdk/variable';


export class VariableWithValues {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):VariableWithValues {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableWithValues(bb:flatbuffers.ByteBuffer, obj?:VariableWithValues):VariableWithValues {
  return (obj || new VariableWithValues()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableWithValues(bb:flatbuffers.ByteBuffer, obj?:VariableWithValues):VariableWithValues {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableWithValues()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

variable():Variable {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Variable.undefined;
}

unit():Unit {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Unit.undefined;
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

values(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

valuesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

valuesArray():Float32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

valuesInt64(index: number):flatbuffers.Long|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : this.bb!.createLong(0, 0);
}

valuesInt64Length():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

altitude():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

aggregation():Aggregation {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Aggregation.none;
}

pressureLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

depth():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

depthTo():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

ensembleMember():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

previousDay():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

static startVariableWithValues(builder:flatbuffers.Builder) {
  builder.startObject(12);
}

static addVariable(builder:flatbuffers.Builder, variable:Variable) {
  builder.addFieldInt8(0, variable, Variable.undefined);
}

static addUnit(builder:flatbuffers.Builder, unit:Unit) {
  builder.addFieldInt8(1, unit, Unit.undefined);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldFloat32(2, value, 0.0);
}

static addValues(builder:flatbuffers.Builder, valuesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, valuesOffset, 0);
}

static createValuesVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createValuesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createValuesVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startValuesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addValuesInt64(builder:flatbuffers.Builder, valuesInt64Offset:flatbuffers.Offset) {
  builder.addFieldOffset(4, valuesInt64Offset, 0);
}

static createValuesInt64Vector(builder:flatbuffers.Builder, data:flatbuffers.Long[]):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]!);
  }
  return builder.endVector();
}

static startValuesInt64Vector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
}

static addAltitude(builder:flatbuffers.Builder, altitude:number) {
  builder.addFieldInt16(5, altitude, 0);
}

static addAggregation(builder:flatbuffers.Builder, aggregation:Aggregation) {
  builder.addFieldInt8(6, aggregation, Aggregation.none);
}

static addPressureLevel(builder:flatbuffers.Builder, pressureLevel:number) {
  builder.addFieldInt16(7, pressureLevel, 0);
}

static addDepth(builder:flatbuffers.Builder, depth:number) {
  builder.addFieldInt16(8, depth, 0);
}

static addDepthTo(builder:flatbuffers.Builder, depthTo:number) {
  builder.addFieldInt16(9, depthTo, 0);
}

static addEnsembleMember(builder:flatbuffers.Builder, ensembleMember:number) {
  builder.addFieldInt16(10, ensembleMember, 0);
}

static addPreviousDay(builder:flatbuffers.Builder, previousDay:number) {
  builder.addFieldInt16(11, previousDay, 0);
}

static endVariableWithValues(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVariableWithValues(builder:flatbuffers.Builder, variable:Variable, unit:Unit, value:number, valuesOffset:flatbuffers.Offset, valuesInt64Offset:flatbuffers.Offset, altitude:number, aggregation:Aggregation, pressureLevel:number, depth:number, depthTo:number, ensembleMember:number, previousDay:number):flatbuffers.Offset {
  VariableWithValues.startVariableWithValues(builder);
  VariableWithValues.addVariable(builder, variable);
  VariableWithValues.addUnit(builder, unit);
  VariableWithValues.addValue(builder, value);
  VariableWithValues.addValues(builder, valuesOffset);
  VariableWithValues.addValuesInt64(builder, valuesInt64Offset);
  VariableWithValues.addAltitude(builder, altitude);
  VariableWithValues.addAggregation(builder, aggregation);
  VariableWithValues.addPressureLevel(builder, pressureLevel);
  VariableWithValues.addDepth(builder, depth);
  VariableWithValues.addDepthTo(builder, depthTo);
  VariableWithValues.addEnsembleMember(builder, ensembleMember);
  VariableWithValues.addPreviousDay(builder, previousDay);
  return VariableWithValues.endVariableWithValues(builder);
}
}
