name: Deploy Vite + Storybook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build
      - name: Move Vite dist
        run: mv dist vite-dist

      - name: Build Storybook
        run: npm run build-storybook
      - name: Move Storybook dist
        run: mv storybook-static storybook-dist

      - name: Merge outputs
        run: |
          mkdir public
          mv vite-dist/* public/
          mkdir public/storybook
          mv storybook-dist/* public/storybook/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
